apiVersion: v1
kind: Service
metadata:
  name: eureka-sample
  namespace: kubesphere-springcloud-sample
  labels:
    app: eureka-sample
spec:
  type: NodePort
  ports:
  - port: 8761
    name: eureka-sample
  selector:
    app: eureka-sample
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka-sample
  namespace: kubesphere-springcloud-sample
spec:
  serviceName: 'eureka-sample'
  podManagementPolicy: Parallel
  # n instances
  replicas: 3
  selector:
    matchLabels:
      app: eureka-sample
      version: master-$BUILD_NUMBER
  template:
    metadata:
      labels:
        app: eureka-sample
        version: master-$BUILD_NUMBER
    spec:
      initContainers:
        - name: wait-config
          image: 'busybox:1.28.4'
          command:
            - sh
            - '-c'
            - >-
              until nc -z config-sample 8080; do echo "waiting for
                            config"; sleep 2; done;
      containers:
        - name: eureka
          image: runzexia/eureka-sample:latest
          ports:
            - containerPort: 8761
          resources:
            limits:
              memory: 2Gi
          env:
            - name: MY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JAVA_OPTS
              value: -XX:+UnlockExperimentalVMOptions
                -XX:+UseCGroupMemoryLimitForHeap
                -XX:MaxRAMFraction=2
                -XX:CICompilerCount=8
                -XX:ActiveProcessorCount=8
                -XX:+UseG1GC
                -XX:+AggressiveOpts
                -XX:+UseFastAccessorMethods
                -XX:+UseStringDeduplication
                -XX:+UseCompressedOops
                -XX:+OptimizeStringConcat
            - name: EUREKA_SERVER
              value: "http://eureka-sample-0.eureka-sample:8761/eureka/,http://eureka-sample-1.eureka-sample:8761/eureka/,http://eureka-sample-2.eureka-sample:8761/eureka/"
            - name: EUREKA_INSTANCE_HOSTNAME
              value: ${MY_POD_NAME}.eureka-sample
            - name: CONFIG_SERVER
              value: "http://config-sample:8080"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 360
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8761
            initialDelaySeconds: 360
            periodSeconds: 10
            timeoutSeconds: 5
